### ISSUE TITLE
关于启动脚本的问题

### ISSUE THREAD

**Issue by yyjob** [blinkfox/jpack-maven-plugin#2]
目前生成的启动脚本start.sh没有检测改项目是否正在运行，重复执行该脚本会重复启动，建议启动前检测改服务status，做出合理的提示（仅测试了linux环境）

**Comment by blinkfox** [comment]
嗯，确实没检查，后续可以加上。

**Comment by blinkfox** [comment]
这个判断在 `1.3.4` 版本已经加上了
